version: '3.9'

services:
  alpha:
    image: alpha:latest
    container_name: alpha
    build: .
    hostname: alpha
    volumes:
      - ./:/opt/alpha
    ports:
      - 3000:3000
    restart: on-failure

networks:
  default:
    name: alpha-core-network
